#! /bin/sh

if [ -z "$1" ]
  then
    echo "No Database Name given !!"
    exit 1
fi

echo "Cleaning Database :  $1"

uuid=$(uuidgen)
echo "Cleaning Database :  $1"
psql -c "UPDATE ir_cron SET active='f';" -d $1
psql -c "UPDATE ir_mail_server SET active='f';" -d $1
psql -c "UPDATE res_users SET login='admin',password='admin',active='t' WHERE id=1;" -d $1
psql -c "UPDATE res_users SET login='admin2',password='admin',active='t' WHERE id=2;" -d $1
psql -c "UPDATE res_users SET login='admin',password=null,active='t',password_crypt='\$pbkdf2-sha512\$25000\$WqsVQiiFkJIyxnjPmTPGGA\$wFyWXkZTOzKD5ZXttnJUuaVJJeLiYRpk5Rf06N6QpH8c7KHGof9OSzjlv4EJLi3U.rxe.ag4QuEPSA7oW6F6Bg' WHERE id=1;" -d $1
psql -c "UPDATE res_users SET login='admin2',password=null,active='t',password_crypt='\$pbkdf2-sha512\$25000\$WqsVQiiFkJIyxnjPmTPGGA\$wFyWXkZTOzKD5ZXttnJUuaVJJeLiYRpk5Rf06N6QpH8c7KHGof9OSzjlv4EJLi3U.rxe.ag4QuEPSA7oW6F6Bg' WHERE id=2;" -d $1
psql -c "UPDATE ir_config_parameter SET value = '2040-01-01 00:00:00' WHERE key = 'database.expiration_date';" -d $1
psql -c "UPDATE ir_config_parameter SET value = '$uuid' WHERE key = 'database.uuid';" -d $1
psql -c "UPDATE ir_ui_view SET active = 'f' WHERE id in (SELECT id FROM ir_ui_view WHERE  name like '%saas trial assets%');" -d $1
psql -c "DELETE FROM ir_attachment WHERE name like '%assets_%';" -d $1


echo "Database $1 is ready Administrator login with username & password : admin (<= v11) and if admin2 (>= v12) and password admin"