#! /bin/sh

if [ -z "$1" ]
  then
    echo "No Database Name given !!"
    exit 1
fi

echo "Cleaning Database :  $1"

psql -c "UPDATE ir_cron SET active='False';" -d $1
psql -c "UPDATE res_users SET login='admin',password='admin' WHERE id=1;" -d $1
psql -c "UPDATE ir_config_parameter SET value='2040-01-01' WHERE key='database.expiration_date';" -d $1
psql -c "UPDATE ir_ui_view SET active = 'f' WHERE id in (SELECT id FROM ir_ui_view WHERE  name like '%saas trial assets%');" -d $1
